name = "puffer-votes"
main = "src/index.js"
compatibility_date = "2026-05-01"

# Replace the id below with the namespace id printed by:
#   wrangler kv:namespace create VOTES
[[kv_namespaces]]
binding = "VOTES"
id = "52cc794c0bc046c185c7971cbe18d393"
